"""update task model

Revision ID: 918788054f55
Revises: a4da57375942
Create Date: 2025-12-29 13:06:28.664863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918788054f55'
down_revision: Union[str, Sequence[str], None] = 'a4da57375942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
